### PR TITLE
Move /admin/content/log View to optional config.

### PR DESCRIPTION
**Pull request by mstenta**
See #23

### CODE REVIEW

**Comment by mstenta** [comment]
Working on a fix for the test fails now...

**Comment by mstenta** [comment]
One of the reasons the test didn't pass is because the LogDeleteForm was redirecting to the View page on delete and cancel. But that also wasn't working even with the View installed. So in my branch I changed LogDeleteForm to extend ContentEntityDeleteForm instead - I think this must have been added recently because Drupal Console uses it by default in entity code that it generates now. But this also means that it currently isn't redirecting to the View at all anymore. Let's see if this passes the tests...

**Comment by mstenta** [comment]
FYI This is not ready to be merged yet...

1) src/Form/DeleteMultiple is still redirecting to the View

2) In both cases, I would like to add a condition that checks to see if the View route exists - and redirect there if so. I'm having trouble figuring out exactly how to do that though...

**Comment by mstenta** [comment]
I added one more commit that simply changes the DeleteMultiple::getCancelUrl() so that it returns the front page URL.

It isn't necessary to link to the View in this context anyway. It will automatically redirect back to the View if that is where you execute the operation from anyway. So it is redundant anyway. Now there is less code, and it still works basically the same.

**Comment by mstenta** [comment]
Force pushed branch to be up-to-date with master.

**Comment by mstenta** [comment]
@zaporylie This is now ready for review! I figure we can figure out this PR as a last step before moving to drupal.org.

**Comment by zaporylie** [comment]
Much cleaner implementation, like it! Merged to master

**Comment by mstenta** [comment]
Thanks @zaporylie !

**Pull request merged**
